"""empty message

Revision ID: 74163700a1b1
Revises: 
Create Date: 2023-10-26 13:23:02.893926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74163700a1b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_table.id'], name=op.f('fk_reviews_table_customer_id_customers_table')),
    sa.ForeignKeyConstraint(['item_id'], ['items_table.id'], name=op.f('fk_reviews_table_item_id_items_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_table')
    op.drop_table('items_table')
    op.drop_table('customers_table')
    # ### end Alembic commands ###
